backend:
  build: .
  dockerfile: backend.Dockerfile
  ports:
    - "8085:8085"
  command: python3 /app/server.py
  links:
    - db

parser:
  build: .
  dockerfile: parser.Dockerfile
  command: python3 -m celery worker -A parser -B -s /tmp/celerybeat-schedule
  environment:
    - C_FORCE_ROOT=true
  links:
    - db
    - backend

db:
  image: mongo:3.0.2
  volumes:
    - /var/lib/mongodb:/data/db

